In [2]:
import numpy as np

In [ ]:
# Producto punto
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_result = np.dot(a, b)
dot_result

32

In [3]:
# Raiz cuadrada
a = np.array([1, 4, 9, 16])
sqrt_result = np.sqrt(a)
sqrt_result

array([1., 2., 3., 4.])

In [ ]:
# Seno y coseno
angles = np.array([0, np.pi/2, np.pi])
sin_result = np.sin(angles)
cos_result = np.cos(angles)
print(sin_result)
print(cos_result)

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [ ]:
# Media
data = np.array([1, 2, 3, 4, 5])
mean_result = np.mean(data)
mean_result

3.0

In [ ]:
# Mediana
data = np.array([1, 2, 3, 4, 5])
median_result = np.median(data)
median_result

3.0

In [ ]:
# Varianza
data = np.array([1, 2, 3, 4, 5])
var_result = np.var(data)
var_result

2.0

In [ ]:
# Desviacion estandar
data = np.array([1, 2, 3, 4, 5])
std_result = np.std(data)
std_result

1.4142135623730951

In [ ]:
# Correlacion
x = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])
corr_result = np.corrcoef(x, y)
corr_result

array([[1., 1.],
       [1., 1.]])