In [2]:
import numpy as np

In [13]:
a = np.array([[[1, 2, 3],[4, 5, 6],[7, 8, 9]],[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
a.dtype

dtype('int64')

In [30]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
b = np.arange(6)
c = b.reshape(3, 2)
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [38]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [39]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])