In [2]:
import numpy as np

def determinant_2x2(matrix):
    # Asegúrate de que la matriz es 2x2
    if matrix.shape == (2, 2):
        return matrix[0, 0] * matrix[1, 1] - matrix[0, 1] * matrix[1, 0]
    else:
        raise ValueError("La matriz no es 2x2")

# Definir una matriz 2x2
A_2x2 = np.array([
    [1, 2],
    [3, 4]
])

# Calcular el determinante
det_2x2 = determinant_2x2(A_2x2)
print(f"Determinante de la matriz 2x2: {det_2x2}")
if det_2x2 != 0:
  print("La matriz es regular")
else:
  print("La matriz es singular")

Determinante de la matriz 2x2: -2
La matriz es regular


In [ ]:
import numpy as np

# Definir una matriz cuadrada
A = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

# Calcular el determinante
determinant = np.linalg.det(A)

if determinant != 0:
    print("La matriz es regular")
    # Calcular la inversa si la matriz es invertible
    A_inv = np.linalg.inv(A)
    print("Matriz original:")
    print(A)
    print("\nMatriz inversa:")
    print(A_inv)
else:
    print("La matriz no es invertible (su determinante es cero).")


La matriz es regular
Matriz original:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Matriz inversa:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]
