In [16]:
import numpy as np

In [17]:
# Sumar elementos de dos arrays de forma independiente
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
sum_result = np.add(a, b)
sum_result

array([ 6,  8, 10, 12])

In [18]:
# Multiplicar elementos de dos arrays de forma independiente
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
prod_result = np.multiply(a, b)
prod_result

array([ 5, 12, 21, 32])

In [19]:
# Sumar todos los elementos de un array
a = np.array([1, 2, 3, 4, 5])
total_sum = np.sum(a)
total_sum

15

In [20]:
# Sumar todos los elementos de un array bidimensional
b = np.array([[1, 2, 3], [4, 5, 6]])
total_sum = np.sum(b)
total_sum

21

In [21]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# Sumar a lo largo de las columnas
sum_cols = np.sum(b, axis=0)
sum_cols

array([5, 7, 9])

In [23]:
# Sumar a lo largo de las filas
sum_rows = np.sum(b, axis=1)
sum_rows

array([ 6, 15])